version: '2'

services:
  nginx:
    build: ./nginx/
    links:
      - node:node
    ports:
      - 80:80
  node:
    build: .
    #command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      SERVER_PORT: ${SERVER_PORT}
      USER: ${USER}
      HOST: ${HOST}
      KEY: ${KEY}
      REF: ${REF}
      REPO: ${REPO}
      APP_PATH: ${APP_PATH}